"use client";

import { useMemo, useState } from "react";
import Image from "next/image";

function SectionHeading({ eyebrow, title, description }) {
  return <div className="mx-auto mb-10 max-w-2xl text-center"><p className="text-sm font-bold text-primary">{eyebrow}</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-secondary sm:text-4xl">{title}</h2><p className="mt-4 text-base leading-7 text-text-body">{description}</p></div>;
}

function VehicleCard({ vehicle }) {
  return <article className="group overflow-hidden rounded-2xl border border-border-100 bg-white transition duration-300 hover:-translate-y-1 hover:shadow-card"><div className="relative h-52 overflow-hidden"><Image src={vehicle.image} alt={vehicle.name} fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1 text-xs font-bold text-secondary">{vehicle.category}</span><button type="button" aria-label={`Save ${vehicle.name}`} className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center rounded-full bg-white text-secondary">♡</button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-extrabold text-secondary">{vehicle.name}</h3><p className="mt-1 text-sm text-text-body">{vehicle.type}</p></div><p className="whitespace-nowrap text-lg font-extrabold text-secondary">${vehicle.price}<span className="text-xs font-medium text-text-body">/day</span></p></div><button type="button" className="mt-5 w-full rounded-lg bg-secondary px-4 py-3 text-sm font-bold text-white transition hover:bg-slate-600">Reserve this car</button></div></article>;
}

export default function FrontHome({ content }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState(content.categories[0]);
  const [searched, setSearched] = useState(false);
  const vehicles = useMemo(() => activeCategory === content.categories[0] ? content.vehicles : content.vehicles.filter((vehicle) => vehicle.category === activeCategory), [activeCategory, content]);

  return <main className="overflow-x-hidden bg-page-bg text-text-heading">
    <header className="sticky top-0 z-20 border-b border-border-100 bg-white/95 backdrop-blur"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" className="text-2xl font-extrabold tracking-tight text-secondary">{content.brand}<span className="text-primary">.</span></a><div className="hidden items-center gap-8 lg:flex">{content.navigation.map((item, index) => <a key={item} href={index === 0 ? "#how-it-works" : index === 1 ? "#fleet" : index === 2 ? "#why-drivo" : "#reviews"} className="text-sm font-bold text-text-body transition hover:text-primary">{item}</a>)}</div><div className="hidden items-center gap-3 sm:flex"><button className="px-3 py-2 text-sm font-bold text-secondary">Sign in</button><button className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white shadow-card">Create account</button></div><button type="button" onClick={() => setMenuOpen((open) => !open)} aria-expanded={menuOpen} aria-label="Toggle menu" className="rounded-lg border border-border-100 p-2 text-secondary lg:hidden">☰</button></nav>{menuOpen && <div className="border-t border-border-100 bg-white px-5 py-4 lg:hidden">{content.navigation.map((item) => <a key={item} href="#fleet" onClick={() => setMenuOpen(false)} className="block py-3 text-sm font-bold text-text-body">{item}</a>)}</div>}</header>

    <section id="top" className="relative"><div className="mx-auto grid max-w-7xl gap-10 px-5 pb-24 pt-16 lg:grid-cols-[.95fr_1.05fr] lg:items-center lg:px-8 lg:py-24"><div><p className="inline-flex rounded-full bg-primary-50 px-3 py-1.5 text-sm font-bold text-primary">{content.hero.eyebrow}</p><h1 className="mt-5 max-w-xl text-5xl font-extrabold leading-[1.04] tracking-tight text-secondary sm:text-6xl">{content.hero.title}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-text-body">{content.hero.description}</p><div className="mt-8 flex flex-wrap gap-4"><a href="#fleet" className="rounded-lg bg-primary px-5 py-3.5 text-sm font-bold text-white shadow-card">Explore our fleet</a><a href="#how-it-works" className="rounded-lg border border-border-100 bg-white px-5 py-3.5 text-sm font-bold text-secondary">How it works</a></div><div className="mt-10 flex gap-8"><p><strong className="block text-2xl font-extrabold text-secondary">20k+</strong><span className="text-sm text-text-body">happy drivers</span></p><p><strong className="block text-2xl font-extrabold text-secondary">150+</strong><span className="text-sm text-text-body">cars available</span></p></div></div><div className="relative min-h-[360px] overflow-hidden rounded-[2rem] bg-secondary shadow-card sm:min-h-[480px]"><Image src={content.hero.image} alt="Premium rental SUV on the road" fill priority sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-secondary/25" /><div className="absolute bottom-5 left-5 rounded-xl bg-white p-4 shadow-card"><p className="text-xs font-bold text-text-body">Rated excellent by</p><p className="mt-1 text-lg font-extrabold text-secondary">4.9/5 <span className="text-primary">★★★★★</span></p></div></div></div>
      <form onSubmit={(event) => { event.preventDefault(); setSearched(true); }} className="relative z-10 mx-5 -mb-10 max-w-7xl rounded-2xl border border-border-100 bg-white p-4 shadow-card lg:mx-auto lg:-mb-12 lg:grid lg:grid-cols-[repeat(4,1fr)_auto] lg:items-end lg:gap-3"><div className="mb-3 flex items-center justify-between lg:col-span-5 lg:mb-1"><p className="text-base font-extrabold text-secondary">Where will you go?</p>{searched && <p className="text-sm font-bold text-success">Cars are ready for your dates</p>}</div>{content.searchFields.map((field) => <label key={field.label} className="mb-3 block rounded-lg border border-border-100 px-3 py-2.5 lg:mb-0"><span className="block text-[11px] font-bold uppercase tracking-wide text-text-body">{field.label}</span><span className="mt-1 block text-sm font-bold text-secondary">{field.value}⌄</span></label>)}<button type="submit" className="w-full rounded-lg bg-primary px-5 py-3.5 text-sm font-bold text-white lg:w-auto">Search cars</button></form>
    </section>

    <section id="how-it-works" className="bg-white px-5 pb-20 pt-28 lg:px-8 lg:pb-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="How it works" title="Rent a car in three easy steps" description="Everything you need to get moving, without the paperwork or the stress." /><div className="grid gap-6 md:grid-cols-3">{content.steps.map((step) => <article key={step.number} className="rounded-2xl bg-page-bg p-7"><span className="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-primary-50 text-base font-extrabold text-primary">{step.number}</span><h3 className="mt-6 text-xl font-extrabold text-secondary">{step.title}</h3><p className="mt-3 leading-7 text-text-body">{step.description}</p></article>)}</div></div></section>

    <section id="fleet" className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Our fleet" title="A car for every kind of trip" description="Choose from carefully maintained vehicles that are ready when you are." /><div className="mb-8 flex flex-wrap justify-center gap-3">{content.categories.map((category) => <button key={category} type="button" onClick={() => setActiveCategory(category)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${activeCategory === category ? "bg-secondary text-white" : "border border-border-100 bg-white text-text-body hover:border-primary hover:text-primary"}`}>{category}</button>)}</div><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{vehicles.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div></div></section>

    <section id="why-drivo" className="bg-secondary px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-80 overflow-hidden rounded-3xl"><Image src={content.vehicles[2].image} alt="Luxury rental car" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div><p className="text-sm font-bold text-primary">Why Drivo</p><h2 className="mt-3 text-4xl font-extrabold tracking-tight text-white">More freedom. Less friction.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/75">We take care of the details so you can enjoy the road ahead.</p><div className="mt-8 space-y-6">{content.benefits.map((benefit, index) => <div key={benefit.title} className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-extrabold text-white">0{index + 1}</span><div><h3 className="font-extrabold text-white">{benefit.title}</h3><p className="mt-1 leading-6 text-white/75">{benefit.description}</p></div></div>)}</div></div></div></section>

    <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-primary p-8 text-white sm:p-10"><p className="text-sm font-bold text-white/80">Need a car this weekend?</p><h2 className="mt-3 max-w-md text-3xl font-extrabold leading-tight">Last-minute plans deserve a great ride.</h2><button className="mt-7 rounded-lg bg-white px-5 py-3 text-sm font-bold text-secondary">Browse available cars</button></article><article className="rounded-3xl bg-primary-50 p-8 sm:p-10"><p className="text-sm font-bold text-primary">For businesses</p><h2 className="mt-3 max-w-md text-3xl font-extrabold leading-tight text-secondary">Flexible fleet solutions for your team.</h2><button className="mt-7 rounded-lg bg-secondary px-5 py-3 text-sm font-bold text-white">Explore business rental</button></article></div></section>

    <section id="reviews" className="bg-white px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Loved by drivers" title="Thousands of happy journeys" description="Real words from people who chose a better way to rent." /><div className="grid gap-6 md:grid-cols-3">{content.testimonials.map((testimonial) => <figure key={testimonial.name} className="rounded-2xl border border-border-100 p-6"><p className="text-primary">★★★★★</p><blockquote className="mt-4 leading-7 text-text-body">“{testimonial.quote}”</blockquote><figcaption className="mt-6"><p className="font-extrabold text-secondary">{testimonial.name}</p><p className="text-sm text-text-body">{testimonial.role}</p></figcaption></figure>)}</div></div></section>

    <footer className="bg-secondary px-5 py-12 text-white lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.5fr_repeat(3,1fr)]"><div><p className="text-2xl font-extrabold">{content.brand}<span className="text-primary">.</span></p><p className="mt-4 max-w-xs text-sm leading-6 text-white/70">Better cars, clearer prices, and more time for the journeys that matter.</p></div>{[["Explore", "Our fleet", "How it works", "Reviews"], ["Support", "Help centre", "Contact us", "Booking policy"], ["Company", "About Drivo", "Careers", "Business rental"]].map(([heading, ...links]) => <div key={heading}><p className="font-extrabold">{heading}</p>{links.map((link) => <a key={link} href="#top" className="mt-3 block text-sm text-white/70 transition hover:text-primary">{link}</a>)}</div>)}</div><div className="mx-auto mt-10 flex max-w-7xl flex-col gap-3 border-t border-white/20 pt-6 text-sm text-white/60 sm:flex-row sm:justify-between"><span>© 2026 Drivo. All rights reserved.</span><span>Privacy · Terms · Cookies</span></div></footer>
  </main>;
}
